### ISSUE TITLE
GHC 8.2.1 support

### ISSUE THREAD

**Issue by bermanjosh** [phadej/boolean-normal-forms#5]
Hi - I noticed that you updated the cabal metadata on hackage to support GHC 8.0.2 (base 4.9). Since it was only a metadata change and not a package change, I'm making a request (instead of a PR) to do the base for GHC 8.2.1(/2) (base 4.10).

I tested this locally, and was able to get the package to compile, but I was unable to run the test-suite. I got errors regarding the import of 'booleanModelLaws', but I wasn't able to find where that module is imported from.

Thanks!

**Comment by phadej** [comment]
Released as https://hackage.haskell.org/package/boolean-normal-forms-0.0.0.2
